---
services:
  - method: GET
    name: google
    url: 'https://google.com'
  - method: POST
    name: amazon
    url: 'https://hello.free.beeceptor.com'
    payload:
      hello: 'Hello'
      world: 'World!'
  - method: GET
    name: netflix
    url: 'https://netflix.com'
timeout: 30
