---
services:
  - name: google
    method: GET
    url: 'https://google.com'
  - name: amazon
    method: POST
    url: 'https://hello.free.beeceptor.com'
    payload:
      hello: 'Hello'
      world: 'World!'
  - name: netflix
    method: GET
    url: 'https://netflix.com'
timeout: 30
